Исаков Федор
urfu-2016/qa-task-05 pull request #4
Opened 2017-05-09 08:02 UTC by FrodoTheTrue

https://frodothetrue.github.io/qa-task-05/

2017-05-16 06:49 UTC, Dotokoto commented on tests/index-test.js
> +    afterEach(function() {
Лучше подготавливать правильное состояние для тестов в beforeEach

2017-05-16 09:50 UTC, Dotokoto commented on index.js
> +  for (var i = 1; i <= 4; i++) {
Не поняла, зачем с 1 до 4, а не с 0 до 3? Если все равно везде вычитаешь единицу из i и j

2017-05-16 09:51 UTC, Dotokoto commented on index.js
> +function printBoard(board, needMargin) {
Мне не нравится название printBoard, тут еще и события навешиваются и много всего происходит

2017-05-16 16:22 UTC, Dotokoto commented on index.js
> +        move.type = 'left';
Я конечно нашла снизу, зачем это. Но сначала выглядит прям очень непонятно )

2017-05-16 16:25 UTC, Dotokoto commented on index.js
> +  var move = canMoveCell(parseInt(cell[0]), parseInt(cell[1]));
Опять же название функции не подходит. По can кажется, что она должна true/false отдавать

2017-05-16 16:30 UTC, Dotokoto commented on tests/index-test.js
> +    it('should render board with 15 visible cells', function () {
В описании теста сказано про visible, но ты просто проверяешь что они есть :) Это слово лишнее

2017-05-16 16:32 UTC, Dotokoto commented on tests/index-test.js
> +        chai.expect(emptyCell).to.be.deep.equal([]);
```chai.expect(emptyCell).to.be.empty```

2017-05-16 16:34 UTC, Dotokoto commented on tests/index-test.js
> +        chai.expect(cells.length).to.be.equal(15);
```chai.expect(cells).to.have.lengthOf(15)```

2017-05-16 16:45 UTC, Dotokoto commented on tests/index-test.js
> +    it('should move cell up if clicked on first cell in second row', function () {
Я бы еще движения вниз и вправо проверила, потому что в коде if в этих местах. Можно на одной и той же ячейке, туда-обратно ее сдвинуть. Правда, тогда получится что тест на сдвиг вправо свалится, если сломался сдвиг влево. Но думаю что это лучше. чем совсем не проверять

2017-05-16 16:46 UTC, Dotokoto commented on tests/index-test.js
> +    it('should contain board with 15 cells and 1-15 numbers', function () {
👍

2017-05-16 16:48 UTC, Dotokoto commented on tests/index-test.js
> +    it('should show modal if all numbers in correct positions and empty cell in last position', function () {
Можно еще добавить  тест на то, что не выдаст победу на неправильную комбинацию

2017-05-16 16:49 UTC, dotokoto requested changes
Посмотрела, можно еще немного доработать тесты

2017-05-20 18:12 UTC, FrodoTheTrue commented
@Dotokoto поправил

2017-05-22 06:21 UTC, Dotokoto commented
Отлично, принято!

2017-05-22 06:21 UTC, closed without merging